# 11장. 예외와 에러처리

에러를 컨트롤 하는 메커니즘
에러 처리하라고 하지않고 예외처리라고 하는 이유는 예상치 못한 상황에 대처하는 방식이기 때문



## 11.1 Error 객체

- 내장된 Error 객체 있음
- 에러처리에 간편하게 사용
- Error 인스턴스를 만들면 에러메세지를 지정
> - : 에러와 통신하는 수단 
> - 예시 ) 이메일 주소의 유효성을 검사하는 함수가 있음 
검사한 이메일 주소가 올바르면 이메일 주소를 문자열로 반환
바르지 않으면 Error 인스턴스 반환
단순함을 위해 앳 기호(@)만 있으면 유효한 이메일 주소로 간주
> - Error 인스턴스를 활용하는 유효하고 유용한 방법
> - 예외처리에 더 자주 사용



```javascript

function validateEmail(email){
     return email.match(/@/)?
        email: 
        new error(`invalid email : ${email}`);
}
//validateEmail('a@naver.com') 
//"a@naver.com"
//validateEmail('a naver.com')
//err

```

이 함수 사용시 instanceof 연산자를 써서 Error 인스턴스가 반환됐는지 확인 에러메세지는 message프로퍼티에 있음

```javascript

const email = "jane@doe.com";

const validateEmail = validateEmail(email);

if(validateEmail instanceof Error){
    console.log(`Error :${validateEmail.message}`);
}else{
    console.log(`Valid email :${validateEmail}`);
}

```


## 11.2 try /catch와 예외처리

- 예외가 있으면 그것을 캐치한다 뜻
- 예시 ) email이 문자열이 아닌 어떤것을 할당한다고 하면 null,숫자,객체 등 문자열이 아닌 무언가가 들어오면 에러  이부분을 대체하면

```javascript

const email = null;

// 에러가 즉시 일어나면 catchansdmfh dlehd

// try 안에 불록문의 숫자는 제한이 없음 
try{
    
    const validateEmail = validateEmail(email);

//validateEmaild을 호출한다음 if문이 실행되지 않음 
    if(validateEmail instanceof Error){
        console.log(`Error :${validateEmail.message}`);
    }else{
        console.log(`Valid email ${validateEmail}`);
    }
//에러가 일어나는 문에서는 catch 블록으로 넘기고 
// 일어나지 않으면 catch블록이 실행되지 않음
}catch(err){
    console.log(`Error ${err.message}`);
}

//Error validateEmail is not defined
//validateEmail('sA@fff')
//"sA@fff"
//validateEmail('sA!fff')
//err

```

## 11.3 에러 일으키기

- 예시 ) 은행 어플리케이션에 사용한 현금인출기능
계좌의 잔고가 요청한 금액보다 적다면 예외를 일으키기

```javascript
function billPay(amount,payee,account){

    if(amount > account.balance ){
        throw new Error("insufficient funds");
        //throwfmf 호출하면 현재 함수는 즉시 실행을 멈춤
    }else{
        account.transfer(payee,account);
        //account.transfer가 호출되지 않으므로 잔고가 부족한데도 현금을 찾아가는 사고는 발행되지 않음
    }
}

```
## 11.4 예외처리와 호출 스택

- 자바스트립트 인터프리터는 프로그램에서 함수를 호출하고 그함수는 다른 함숭를 호출하고 호출된 함수는 또다른 함수를 호출하는 일이 반복
 함수가 a가 함수 b > b함수가 c함수 호출 > 함수c가 실행을 마칠때 실행 흐름은 함수 b > b실행 마친후 함수a로 돌아옴

- 즉, c 가 실행중일때 a,b가 완료될수 없음 : 호출 스택


- 자바스크립트 환경에서는 Error인스턴스에 슽개 문자열을 표현하면 stack 프로퍼티가 있음  대부분 환경에서 지원


```javascript

function a(){
    console.log(`a : calling b `);
    b();
    console.log(`a : done`);
}

function b(){
    console.log(`b : calling b `);
    c();
    console.log(`b : done`);
}

function c(){
    console.log(`c : throwing error`);
    c();
    throw new Error(`c error`);
    console.log(`c : done`);
}

function d(){
    console.log(`d : calling c`);
    c();
    console.log(`d : done`);
}

try{
    a();
}catch(err){
    console.log(err.stack);
}

try{
    d();
}catch(err){
    console.log(err.stack);
}
// a : calling b 
// b : calling b 
// c : throwing error... 무한...

```

## 11.5 try /catch...finally

- try 블록 문에는 원한는 만큼 쓸수 있고 그중 어디서든 에러가 일어나서 자원을 해체할 기회가 아예 사라질 수있으므로 try 블록에서 자원을 해체하는건 안전하지않음
에러가 일어나지 않으면 실행되지 않는 catch 블록문 역시 안전하지 않음 이러한 사황에는 finally 블록이 필요



```javascript


try{
    console.log("this line is executed...");
    //throw new Error("whoops");
    console.log("this line not...");
}catch(err){
    console.log("threr was an error...");
}finally{
    console.log("....always executed...");
    console.log("perform cleanup here");
}

//this line is executed...
// this line not...
//....always executed...
// perform cleanup here

```